###
GET http://localhost:30030/api/collections

###
GET http://localhost:30030/api/collections/collection/63ee43f5d3f5efa621a7ae21
###
POST http://localhost:30030/api/collections/collection
Content-Type: application/json

{
  "name": "Pruebapaborrar",
  "description": "poiopipoi videogames in my collection",
  "itemsCount": "123123"
}

###
POST http://localhost:30030/api/collections/collection
Content-Type: application/json

{
  "name": "Consoles",
  "description": "All consoles in my collection",
  "itemsCount": "15"
}

###
POST http://localhost:30030/api/collections/collection
Content-Type: application/json

{
  "name": "Funko's",
  "description": "All Funko Pop in my collection",
  "itemsCount": "17"
}

###
POST http://localhost:30030/api/collections/collection
Content-Type: application/json

{
  "name": "Films & Series",
  "description": "All films & series in my collection",
  "itemsCount": "8"
}

###
DELETE  http://localhost:30030/api/collections/collection/63f2b908f3a46ae7af555607

###
GET http://localhost:30030/api/collections/greater