###
GET http://localhost:30030/api/collections

###
GET http://localhost:30030/api/collections/63ee4445d3f5efa621a7ae23
###
POST http://localhost:30030/api/collections
Content-Type: application/json

{
  "name": "Videogames",
  "description": "All videogames in my collection",
  "itemsCount": "60"
}

###
POST http://localhost:30030/api/collections
Content-Type: application/json

{
  "name": "Consoles",
  "description": "All consoles in my collection",
  "itemsCount": "15"
}

###
POST http://localhost:30030/api/collections
Content-Type: application/json

{
  "name": "Funko's",
  "description": "All Funko Pop in my collection",
  "itemsCount": "17"
}

###
POST http://localhost:30030/api/collections
Content-Type: application/json

{
  "name": "Films & Series",
  "description": "All films & series in my collection",
  "itemsCount": "8"
}